version: "3.9"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    command: ["npx", "nodemon", "server.js"]
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=kiit@123
      - DB_NAME=task_dashboard
      - DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kiit@123
      POSTGRES_DB: task_dashboard
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
