services:
  server:
  
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env 
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=kiit@123
      - DB_NAME=task_dashboard
      - DB_HOST=postgres
    depends_on:
      - postgres

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kiit@123
      POSTGRES_DB: task_dashboard
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
